### ISSUE TITLE
Removed expired tokens will end in anonymous requests

### ISSUE THREAD

**Issue by elioschmutz** [4teamwork/ftw.tokenauth#14]
The [`authenticateCredential` method of the PAS-Plugin](https://github.com/4teamwork/ftw.tokenauth/blob/master/ftw/tokenauth/pas/plugin.py#L189) tries to login the given user with a bearer token. If the token is expired, it will [raise a 401 with the specific error message](https://github.com/4teamwork/ftw.tokenauth/blob/master/ftw/tokenauth/pas/plugin.py#L217).

If the token is not found at all it will do nothing (the developer was aware of that, that it should probably do something): https://github.com/4teamwork/ftw.tokenauth/blob/master/ftw/tokenauth/pas/plugin.py#L210

After issuing a new token, all expired tokens will be cleaned up: https://github.com/4teamwork/ftw.tokenauth/blob/master/ftw/tokenauth/pas/plugin.py#L126

This means, that if there will be a user with an expired access token and a new user is trying to obtain a new token, the token of user 1 gets removed. If the first user then tries to access some content, the `ftw.tokenauth` wont return a `401 - token expired`. It will just skip the auth-plugin. The user is not logged in anymore and is doing the request anonymously. We're not able to renew the token because we don't know about the expired token from on the client side.

**Comment by lukasgraf** [comment]
Thanks for the detailed analysis! As you pointed out, I did notice this edge case and wasn't quite sure about how exactly to handle it.

After thinking about it some more, I believe the current implementation is correct (as least the best we can do).

The way PAS works, is that, after credentials have been extracted from the request, all authentication plugins get a chance to perform authentication using those credentials (in the order they are configured in the plugin registry). The first plugin that succeeds will log the user in. If no plugin succeeds, PAS will keep the user `Anonymous`.

If `Anonymous` doesn't have the required permissions, a generic 401 response will then be returned by Plone (or `plone.rest` in the case of API rewuests). Which is what we're seeing in the case where the tokens have already been cleaned.

Now, in `ftw.tokenauth` we can confidently reject an expired token with a specific message. We found the token in our storage, but its just not valid anymore. If we don't find the token however, we can't really be sure whether it's expired, or the request was performed using an authentication method that simply wasn't meant for us (`ftw.tokenauth`).

All we have to go on is an `Authorization: Bearer <token>` header. If we find that token in the storage, we can be very sure that it was meant for `ftw.tokenauth`. But if we don't, it could just as well be intended for a different authentication plugin that also uses the `Authorization: Bearer ..." scheme (that's a very generic scheme). If `ftw.tokenauth` would actively reject such requests with its own 401 response, it would take away the chance for all plugins later in the chain to authenticate the request.

So the way PAS works it's usually best for Plugins to only actively reject requests if the can be very sure that the authentication method was intended for them. Otherwise it's better to have it fall through. And the `Authorization: Bearer ..." scheme is mandated by OAuth2, that's not something we can change.

I therefore believe the best course of action is to handle this on the client side, and just check for `401`, not necessarily a specific message (plus a cycle breaker).

**Comment by elioschmutz** [comment]
@lukasgraf generally, I agree with your response and I also think we have to handle 401 errors in general on the client side.

But I have a question about handling expired tokens: According to OAuth2, the server should return a `token invalid` error if the used token is expired. This means, we have to always keep issued tokens. Additionally, OAuth2 declares `refresh_tokens` for token renewal. We should use the `refresh_token` to reoptain an expired token. But this also requires to keep issued tokens. Otherwise, we're not able to detect expired tokens.

Graphic from https://tools.ietf.org/html/rfc6749#section-1.5

<img width="582" alt="Bildschirmfoto 2020-02-26 um 10 51 34" src="https://user-images.githubusercontent.com/557005/75333201-ff93ea80-5885-11ea-81e5-044d09569ece.png">

What does this mean for us now? How strong are the OAuth2 specs? Should we implement `refresh_tokens` or is our implementation still a valid OAuth2 implementation? We can assume, that the client will never get a token expiration error because expired tokens will always cleaned up if someone is logging in. But with my understanding according to the OAuth2 specs, it should...

**Comment by lukasgraf** [comment]
It's a bit more complicated than that unfortunately 😉 OAuth2 is not just a single spec (RFC), it's a authentication framework that consist of several parts, many of them optional. OAuth2 is also rather loose on some specific details, unfortunately.

Refresh tokens are a different kind of token than access tokens (and they're an optional part of the implementation). They are intended for more complex integration scenarios where the Authorization server is different from the Resource Server (which is not the case in our situation). They offer some additional flexibility which we simply don't currently need, but they wouldn't solve this token.

So this graphic doesn't apply here, because that's not the flow that `ftw.tokenauth` implements. (The relevant, more generic flow for `ftw.tokenauth` is outlined [here](https://github.com/4teamwork/ftw.tokenauth/blob/b387009f8c3298346d8a7a3729662106d126be20/ftw/tokenauth/oauth2/browser/oauth2_token.py#L51-L74))

So yes, it's a compliant OAuth2 implementation. It's just that the RFCs cover the most simple case, where OAuth2 is the single and only authentication mechanism that's being implemented. This is obviously not the case with a pluggable system like PAS, that supports several authentication methods at once, and this means that the specification has to be adapted for those real-world situations when integrating OAuth2 into a sytem like Plone. For this reason, it's unavoidable in some places to not follow certain RFCs verbatim ([here](https://github.com/4teamwork/ftw.tokenauth/blob/b387009f8c3298346d8a7a3729662106d126be20/ftw/tokenauth/pas/plugin.py#L198-L204) for example).

Now, keeping around issued tokens forever would obviously simplify the situation, but you just can't do that. So they eventually need to be cleaned up. And at least with this implementation it's "pretty obvious" when this is happening, because it happens soon. Imagine we would keep the tokens around longer (say, just the last 1000). Then every month or so one random request would fail in a weird way. Imagine how difficult that would have been to debug 😉 

> the server should return a token invalid error if the used token is expired

Yes, `SHOULD`, not `MUST`.

**Comment by elioschmutz** [comment]
@lukasgraf 👍 thanks for your response!

So I think, we can close this issue.
